travis:
  secure:
    BINSTAR_TOKEN: eiyJWvddJzD8UvIoUKS2nPYRYXpSS9QsvXKfn7FARbX6i5+NXr8jX+9RdMPhcd4dIq1WyPLCsFNBMtWRGea3ftehaFY0RY+PFxMYVa4EnZ6TpUerBIoDJ6BCJR57/dyP7iXHASZGU1P8dD7tE9Vxkv143Oq7F1rnuXINsawbAlX07oj/dzuq9848TzBvTfNUanqsSZGUkpIu5glFAyTesXDLQ9ho2t7qjuW2m2GWFv6rV8SWerY2wLalEgWTjAh2PDGH5l+lla7jQey+yO2EtlYl6b+xdg6Nps16Dsng50UZO7Smh2WHQ5VX6BeQIWTDjGYeF06atmcifdHJlhizJhWSJAfzsASwcHwaud/YZ/bCmy7MGrDHvPtKAh9SQg4RgUqKTGafFZ7tnaS1vDdJ/iUuKqZUgGn4FoSqpRiyMJzjI0sajV9FBASEHjw/kDogmMeIvPdWpX+zavel9BSlvCupQIDkmih+khr7/KnVxoDFo+82IS9JML7KqJwzLDmoHsIUcGhuhUax7jJlN1fXxeEJE4igcXDtxnQThTO16yuUn510ABDWf3PzbBA/BEk+AuZX4Rc5fZn2VkbaW2orbI15QUujDiORNz7xQAarNb4dKgRP//RF7sIFcQkI6w8v7iyRAeqpv7QHYNwHRkWB349ivaYZ1m3JJJB43ZnC/HQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
